spring.application.name=semana2


# === MySQL local ===
spring.datasource.url=jdbc:mysql://localhost:3306/seguridad_calidad?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Santiago&useUnicode=true&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=morande2101.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# === JPA/Hibernate ===
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# === JWT ===
security.jwt.secret=DSy6ctQ219g7I9S0hOctZRzEC5eOG3VKLa1A2uDtW18C5JeJurpyH6hSb/9PSxVGq3DMwq3JWu5728vuIns4PQ==
security.jwt.expiration-minutes=120

# (Opcional) CORS rápido si consumirás desde un front externo
# spring.web.cors.allowed-origins=http://localhost:5173
# spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
# spring.web.cors.allowed-headers=*
