-- ================================
-- TABLA USUARIOS
-- ================================
DROP TABLE IF EXISTS usuarios_favoritos;
DROP TABLE IF EXISTS receta_fotos;
DROP TABLE IF EXISTS recetas;
DROP TABLE IF EXISTS usuarios;

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    password VARCHAR(255),
    email VARCHAR(255),
    nombre VARCHAR(255),
    nombre_completo VARCHAR(255),
    titulo VARCHAR(255),
    biografia VARCHAR(2000),
    rol VARCHAR(255),
    fecha_registro TIMESTAMP
);

-- ================================
-- TABLA RECETAS
-- ================================
CREATE TABLE recetas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    tipo_cocina VARCHAR(255),
    pais VARCHAR(255),
    dificultad VARCHAR(255),
    emoji VARCHAR(255),
    tiempo_preparacion INTEGER,
    tiempo_coccion INTEGER,
    porciones INTEGER,
    calorias INTEGER,
    vistas INTEGER,
    likes INTEGER,
    publica BOOLEAN,
    fecha_creacion TIMESTAMP,
    ingredientes VARCHAR(2000),
    instrucciones VARCHAR(5000),
    descripcion VARCHAR(2000),
    usuario_id BIGINT,
    CONSTRAINT fk_receta_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

-- ================================
-- TABLA COLECCIÓN: receta_fotos
-- ================================
CREATE TABLE receta_fotos (
    receta_id BIGINT NOT NULL,
    emoji_foto VARCHAR(255),
    CONSTRAINT fk_receta_fotos_receta FOREIGN KEY (receta_id) REFERENCES recetas(id)
);

-- ================================
-- TABLA MANY-TO-MANY: usuarios_favoritos
-- ================================
CREATE TABLE usuarios_favoritos (
    usuario_id BIGINT NOT NULL,
    receta_id BIGINT NOT NULL,
    CONSTRAINT fk_uf_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_uf_receta FOREIGN KEY (receta_id) REFERENCES recetas(id)
);
